/* ============================================ */
/* Runes : icones officielles (assets locaux)   */
/* Source : api.dofusdb.fr, copiees dans        */
/* site/assets/images/runes/                    */
/* ============================================ */

ALTER TABLE public.runes
    ADD COLUMN IF NOT EXISTS img_url TEXT DEFAULT NULL;

UPDATE public.runes SET img_url = 'assets/images/runes/78043.png' WHERE nom = 'Rune Fo';
UPDATE public.runes SET img_url = 'assets/images/runes/78049.png' WHERE nom = 'Rune Sa';
UPDATE public.runes SET img_url = 'assets/images/runes/78037.png' WHERE nom = 'Rune Ine';
UPDATE public.runes SET img_url = 'assets/images/runes/78052.png' WHERE nom = 'Rune Vi';
UPDATE public.runes SET img_url = 'assets/images/runes/78046.png' WHERE nom = 'Rune Age';
UPDATE public.runes SET img_url = 'assets/images/runes/78040.png' WHERE nom = 'Rune Cha';
UPDATE public.runes SET img_url = 'assets/images/runes/78044.png' WHERE nom = 'Rune Pa Fo';
UPDATE public.runes SET img_url = 'assets/images/runes/78050.png' WHERE nom = 'Rune Pa Sa';
UPDATE public.runes SET img_url = 'assets/images/runes/78038.png' WHERE nom = 'Rune Pa Ine';
UPDATE public.runes SET img_url = 'assets/images/runes/78053.png' WHERE nom = 'Rune Pa Vi';
UPDATE public.runes SET img_url = 'assets/images/runes/78047.png' WHERE nom = 'Rune Pa Age';
UPDATE public.runes SET img_url = 'assets/images/runes/78041.png' WHERE nom = 'Rune Pa Cha';
UPDATE public.runes SET img_url = 'assets/images/runes/78045.png' WHERE nom = 'Rune Ra Fo';
UPDATE public.runes SET img_url = 'assets/images/runes/78051.png' WHERE nom = 'Rune Ra Sa';
UPDATE public.runes SET img_url = 'assets/images/runes/78039.png' WHERE nom = 'Rune Ra Ine';
UPDATE public.runes SET img_url = 'assets/images/runes/78054.png' WHERE nom = 'Rune Ra Vi';
UPDATE public.runes SET img_url = 'assets/images/runes/78048.png' WHERE nom = 'Rune Ra Age';
UPDATE public.runes SET img_url = 'assets/images/runes/78042.png' WHERE nom = 'Rune Ra Cha';
UPDATE public.runes SET img_url = 'assets/images/runes/78055.png' WHERE nom = 'Rune Ga Pa';
UPDATE public.runes SET img_url = 'assets/images/runes/78056.png' WHERE nom = 'Rune Ga Pme';
UPDATE public.runes SET img_url = 'assets/images/runes/78014.png' WHERE nom = 'Rune Cri';
UPDATE public.runes SET img_url = 'assets/images/runes/78013.png' WHERE nom = 'Rune So';
UPDATE public.runes SET img_url = 'assets/images/runes/78015.png' WHERE nom = 'Rune Do';
UPDATE public.runes SET img_url = 'assets/images/runes/78016.png' WHERE nom = 'Rune Pui';
UPDATE public.runes SET img_url = 'assets/images/runes/78017.png' WHERE nom = 'Rune Do Ren';
UPDATE public.runes SET img_url = 'assets/images/runes/78018.png' WHERE nom = 'Rune Po';
UPDATE public.runes SET img_url = 'assets/images/runes/78019.png' WHERE nom = 'Rune Invo';
UPDATE public.runes SET img_url = 'assets/images/runes/78020.png' WHERE nom = 'Rune Pod';
UPDATE public.runes SET img_url = 'assets/images/runes/78021.png' WHERE nom = 'Rune Pa Pod';
UPDATE public.runes SET img_url = 'assets/images/runes/78022.png' WHERE nom = 'Rune Ra Pod';
UPDATE public.runes SET img_url = 'assets/images/runes/78268.png' WHERE nom = 'Rune Do Pi';
UPDATE public.runes SET img_url = 'assets/images/runes/78024.png' WHERE nom = 'Rune Per Pi';
UPDATE public.runes SET img_url = 'assets/images/runes/78025.png' WHERE nom = 'Rune Ini';
UPDATE public.runes SET img_url = 'assets/images/runes/78026.png' WHERE nom = 'Rune Pa Ini';
UPDATE public.runes SET img_url = 'assets/images/runes/78027.png' WHERE nom = 'Rune Ra Ini';
UPDATE public.runes SET img_url = 'assets/images/runes/78036.png' WHERE nom = 'Rune Prospe';
UPDATE public.runes SET img_url = 'assets/images/runes/78028.png' WHERE nom = 'Rune Ré Feu';
UPDATE public.runes SET img_url = 'assets/images/runes/78032.png' WHERE nom = 'Rune Ré Air';
UPDATE public.runes SET img_url = 'assets/images/runes/78030.png' WHERE nom = 'Rune Ré Eau';
UPDATE public.runes SET img_url = 'assets/images/runes/78034.png' WHERE nom = 'Rune Ré Terre';
UPDATE public.runes SET img_url = 'assets/images/runes/78057.png' WHERE nom = 'Rune Ré Neutre';
UPDATE public.runes SET img_url = 'assets/images/runes/78029.png' WHERE nom = 'Rune Ré Per Feu';
UPDATE public.runes SET img_url = 'assets/images/runes/78033.png' WHERE nom = 'Rune Ré Per Air';
UPDATE public.runes SET img_url = 'assets/images/runes/78035.png' WHERE nom = 'Rune Ré Per Terre';
UPDATE public.runes SET img_url = 'assets/images/runes/78058.png' WHERE nom = 'Rune Ré Per Neutre';
UPDATE public.runes SET img_url = 'assets/images/runes/50037.png' WHERE nom = 'Rune de Signature';
UPDATE public.runes SET img_url = 'assets/images/runes/78031.png' WHERE nom = 'Rune Ré Per Eau';
UPDATE public.runes SET img_url = 'assets/images/runes/78059.png' WHERE nom = 'Rune de chasse';
UPDATE public.runes SET img_url = 'assets/images/runes/78023.png' WHERE nom = 'Rune Pa Do Pi';
UPDATE public.runes SET img_url = 'assets/images/runes/78266.png' WHERE nom = 'Rune Pa Per Pi';
UPDATE public.runes SET img_url = 'assets/images/runes/78267.png' WHERE nom = 'Rune Ra Per Pi';
UPDATE public.runes SET img_url = 'assets/images/runes/78269.png' WHERE nom = 'Rune Pa Pui';
UPDATE public.runes SET img_url = 'assets/images/runes/78270.png' WHERE nom = 'Rune Ra Pui';
UPDATE public.runes SET img_url = 'assets/images/runes/78271.png' WHERE nom = 'Rune Pa Prospe';
UPDATE public.runes SET img_url = 'assets/images/runes/78076.png' WHERE nom = 'Rune Fui';
UPDATE public.runes SET img_url = 'assets/images/runes/78075.png' WHERE nom = 'Rune Pa Fui';
UPDATE public.runes SET img_url = 'assets/images/runes/78077.png' WHERE nom = 'Rune Tac';
UPDATE public.runes SET img_url = 'assets/images/runes/78078.png' WHERE nom = 'Rune Pa Tac';
UPDATE public.runes SET img_url = 'assets/images/runes/78083.png' WHERE nom = 'Rune Ré Pa';
UPDATE public.runes SET img_url = 'assets/images/runes/78084.png' WHERE nom = 'Rune Pa Ré Pa';
UPDATE public.runes SET img_url = 'assets/images/runes/78085.png' WHERE nom = 'Rune Ré Pme';
UPDATE public.runes SET img_url = 'assets/images/runes/78086.png' WHERE nom = 'Rune Pa Ré Pme';
UPDATE public.runes SET img_url = 'assets/images/runes/78087.png' WHERE nom = 'Rune Ret Pa';
UPDATE public.runes SET img_url = 'assets/images/runes/78088.png' WHERE nom = 'Rune Pa Ret Pa';
UPDATE public.runes SET img_url = 'assets/images/runes/78089.png' WHERE nom = 'Rune Ret Pme';
UPDATE public.runes SET img_url = 'assets/images/runes/78090.png' WHERE nom = 'Rune Pa Ret Pme';
UPDATE public.runes SET img_url = 'assets/images/runes/78081.png' WHERE nom = 'Rune Do Pou';
UPDATE public.runes SET img_url = 'assets/images/runes/78082.png' WHERE nom = 'Rune Pa Do Pou';
UPDATE public.runes SET img_url = 'assets/images/runes/78079.png' WHERE nom = 'Rune Ré Pou';
UPDATE public.runes SET img_url = 'assets/images/runes/78080.png' WHERE nom = 'Rune Pa Ré Pou';
UPDATE public.runes SET img_url = 'assets/images/runes/78073.png' WHERE nom = 'Rune Do Cri';
UPDATE public.runes SET img_url = 'assets/images/runes/78074.png' WHERE nom = 'Rune Pa Do Cri';
UPDATE public.runes SET img_url = 'assets/images/runes/78071.png' WHERE nom = 'Rune Ré Cri';
UPDATE public.runes SET img_url = 'assets/images/runes/78072.png' WHERE nom = 'Rune Pa Ré Cri';
UPDATE public.runes SET img_url = 'assets/images/runes/78065.png' WHERE nom = 'Rune Do Terre';
UPDATE public.runes SET img_url = 'assets/images/runes/78066.png' WHERE nom = 'Rune Pa Do Terre';
UPDATE public.runes SET img_url = 'assets/images/runes/78063.png' WHERE nom = 'Rune Do Feu';
UPDATE public.runes SET img_url = 'assets/images/runes/78064.png' WHERE nom = 'Rune Pa Do Feu';
UPDATE public.runes SET img_url = 'assets/images/runes/78061.png' WHERE nom = 'Rune Do Eau';
UPDATE public.runes SET img_url = 'assets/images/runes/78062.png' WHERE nom = 'Rune Pa Do Eau';
UPDATE public.runes SET img_url = 'assets/images/runes/78067.png' WHERE nom = 'Rune Do Air';
UPDATE public.runes SET img_url = 'assets/images/runes/78068.png' WHERE nom = 'Rune Pa Do Air';
UPDATE public.runes SET img_url = 'assets/images/runes/78069.png' WHERE nom = 'Rune Do Neutre';
UPDATE public.runes SET img_url = 'assets/images/runes/78070.png' WHERE nom = 'Rune Pa Do Neutre';
UPDATE public.runes SET img_url = 'assets/images/runes/78092.png' WHERE nom = 'Rune Do Per Mé';
UPDATE public.runes SET img_url = 'assets/images/runes/78091.png' WHERE nom = 'Rune Do Per Di';
UPDATE public.runes SET img_url = 'assets/images/runes/78093.png' WHERE nom = 'Rune Do Per Ar';
UPDATE public.runes SET img_url = 'assets/images/runes/78094.png' WHERE nom = 'Rune Do Per So';
UPDATE public.runes SET img_url = 'assets/images/runes/78095.png' WHERE nom = 'Rune Ré Per Mé';
UPDATE public.runes SET img_url = 'assets/images/runes/78096.png' WHERE nom = 'Rune Ré Per Di';
UPDATE public.runes SET img_url = 'assets/images/runes/78099.png' WHERE nom = 'Rune Pa So';
UPDATE public.runes SET img_url = 'assets/images/runes/78100.png' WHERE nom = 'Rune Pa Ré Air';
UPDATE public.runes SET img_url = 'assets/images/runes/78101.png' WHERE nom = 'Rune Pa Ré Eau';
UPDATE public.runes SET img_url = 'assets/images/runes/78102.png' WHERE nom = 'Rune Pa Ré Feu';
UPDATE public.runes SET img_url = 'assets/images/runes/78103.png' WHERE nom = 'Rune Pa Ré Neutre';
UPDATE public.runes SET img_url = 'assets/images/runes/78104.png' WHERE nom = 'Rune Pa Ré Terre';
UPDATE public.runes SET img_url = 'assets/images/runes/78272.png' WHERE nom = 'Rune Ra Ré Pou';
UPDATE public.runes SET img_url = 'assets/images/runes/78273.png' WHERE nom = 'Rune Ra Do Pou';
UPDATE public.runes SET img_url = 'assets/images/runes/78294.png' WHERE nom = 'Rune Ra Ré Terre';
UPDATE public.runes SET img_url = 'assets/images/runes/78293.png' WHERE nom = 'Rune Ra Ré Neutre';
UPDATE public.runes SET img_url = 'assets/images/runes/78295.png' WHERE nom = 'Rune Ra Ré Feu';
UPDATE public.runes SET img_url = 'assets/images/runes/78296.png' WHERE nom = 'Rune Ra Ré Eau';
UPDATE public.runes SET img_url = 'assets/images/runes/78292.png' WHERE nom = 'Rune Ra Ré Cri';
UPDATE public.runes SET img_url = 'assets/images/runes/78297.png' WHERE nom = 'Rune Ra Ré Air';
UPDATE public.runes SET img_url = 'assets/images/runes/78017.png' WHERE nom = 'Rune Pa Do Ren';
